var ActionNames = {
    CHANGE_LOADING: 'CHANGE_LOADING',
    ACTION_FAILED: 'ACTION_FAILED',

    CHANGE_BOOK: 'CHANGE_BOOK',
    CREATE_BOOK: 'CREATE_BOOK',
    LOAD_BOOK: 'LOAD_BOOK',
    LOAD_BOOKS: 'LOAD_BOOKS',
    REMOVE_BOOK: 'REMOVE_BOOK',
    RECEIVE_BOOK: 'RECEIVE_BOOK',
    RECEIVE_BOOKS: 'RECEIVE_BOOKS',
    UPDATE_BOOK: 'UPDATE_BOOK',

    ADD_FILE: 'ADD_FILE',
    REMOVE_FILE: 'REMOVE_FILE',
    UPLOAD_FILE: 'UPLOAD_FILE',
    UPLOAD_FILE_PREVIEW: 'UPLOAD_FILE_PREVIEW',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_PROGRESS: 'UPLOAD_FILE_PROGRESS',

    SEE_MORE_BOOKS: 'SEE_MORE_BOOKS'
};

module.exports = ActionNames;