var ActionNames = {
    CHANGE_LOADING: 'CHANGE_LOADING',
    ACTION_FAILED: 'ACTION_FAILED',

    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    RECEIVE_CATEGORIES: 'RECEIVE_CATEGORIES',
    LOAD_ITEMS_BY_CATEGORY: 'LOAD_ITEMS_BY_CATEGORY',
    RECEIVE_ITEMS: 'RECEIVE_ITEMS',

    RECEIVE_BG_IMAGES: 'RECEIVE_BG_IMAGES'
};

module.exports = ActionNames;